NXdrive.Web/Models/Shared/AlertBoxModel.cs
using System;
using System.Collections.Generic;

namespace NXdrive.Web.Models.Shared
{
    public class AlertBoxModel : Nop.Web.Framework.Models.BaseNopModel
    {
        public AlertBoxModel()
        {
            ActionList = new List<Tuple<string, string>>();
        }

        public AlertBoxModel(IEnumerable<Tuple<string, string>> actions)
        {
            ActionList = actions;
        }

        public string Title { get; set; }

        public AlertTypeEnum AlertType { get; set; }

        public string Opening { get; set; }
        public string Message { get; set; }

        public IEnumerable<Tuple<string, string>> ActionList { get; set; }

        public enum AlertTypeEnum
        {
            Success = 1,
            Info = 2,
            Warning = 3,
            Error = 4
        }
    }
}

NXdrive.Web/Components/ZenithFooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Web.Framework.Components;
using Polpware.NopWeb.Factories;

namespace NXdrive.Web.Components
{
    public class ZenithFooterViewComponent : NopViewComponent
    {
        private readonly ICommonModelFactory _commonModelFactory;

        public ZenithFooterViewComponent(ICommonModelFactory commonModelFactory)
        {
            this._commonModelFactory = commonModelFactory;
        }

        public IViewComponentResult Invoke(string version = "Default")
        {
            var model = _commonModelFactory.PrepareHeaderLinksModel();
            return View(version, model);
        }
    }
}

NXdrive.Web/Components/ZenithHeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Customers;
using Nop.Core.Domain.Media;
using Nop.Services.Common;
using Nop.Services.Media;
using Nop.Web.Framework.Components;
using Polpware.NopWeb.Factories;

namespace NXdrive.Web.Components
{
    public class ZenithHeaderViewComponent : NopViewComponent
    {
        private readonly ICommonModelFactory _commonModelFactory;
        private readonly ICustomerModelFactory _customerModelFactory;
        private readonly IWorkContext _workContext;
        private readonly IPictureService _pictureService;

        public ZenithHeaderViewComponent(ICommonModelFactory commonModelFactory,
            ICustomerModelFactory customerModelFactory,
            IWorkContext workContext,
            IPictureService pictureService)
        {
            this._commonModelFactory = commonModelFactory;
            _customerModelFactory = customerModelFactory;
            _workContext = workContext;
            _pictureService = pictureService;
        }

        public IViewComponentResult Invoke(string version = "Default")
        {
            var model = _commonModelFactory.PrepareHeaderLinksModel();
            // Avatar model
            if (_workContext.CurrentCustomer.IsRegistered())
            {
                var avatarModel = new Polpware.NopWeb.Models.Customer.CustomerAvatarModel();

                avatarModel.AvatarUrl = Url.RouteUrl("CustomerLoadAvatar", new { id = _workContext.CurrentCustomer.CustomerGuid.ToString() });
                var imageId = _workContext.CurrentCustomer.GetAttribute<int>(SystemCustomerAttributeNames.AvatarPictureId);

                // Read from the image title attributes, as we have used it for storing ticks
                if (imageId > 0)
                {
                    var image = _pictureService.GetPictureById(imageId);
                    avatarModel.AvatarUrl = avatarModel.AvatarUrl + "?v=" + (image == null ? "" : (image.TitleAttribute ?? ""));
                }

                model.CustomProperties.Add("AvatarUrl", avatarModel.AvatarUrl);
            }

            return View(version, model);
        }
    }
}

NXdrive.Web/Components/ZenithLogoViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Web.Framework.Components;
using Polpware.NopWeb.Factories;

namespace NXdrive.Web.Components
{
    public class ZenithLogoViewComponent : NopViewComponent
    {
        private readonly ICommonModelFactory _commonModelFactory;

        public ZenithLogoViewComponent(ICommonModelFactory commonModelFactory)
        {
            this._commonModelFactory = commonModelFactory;
        }

        public IViewComponentResult Invoke(string version = "Default")
        {
            var model = _commonModelFactory.PrepareLogoModel();
            return View(version, model);
        }
    }
}

NXdrive.Web/Views/Shared/Message4LightPage.cshtml
@model AlertBoxModel
@using NXdrive.Web.Models.Shared
@{
    Layout = "_Root4LightPage";

    //title
    Html.AddTitleParts("Message");
    //page class
    Html.AppendPageCssClassParts("message-page");

}
<section class="container g-py-100--md">
    <div class="row justify-content-center">
        <div class="col-sm-10 col-md-9 col-lg-6">
            <div class="g-brd-around g-brd-gray-light-v4 rounded g-py-40 g-px-30">
                <header class="text-center mb-4">
                    <vc:zenith-logo version="Default"></vc:zenith-logo>
                    <h3 class="h3 g-color-black g-font-weight-600 mt-4">@Model.Title</h3>
                </header>

                @{
                    // Compute alert class and icon class
                    var alertTypeClass = string.Empty;
                    var alertIconClass = string.Empty;

                    switch (Model.AlertType)
                    {
                        case AlertBoxModel.AlertTypeEnum.Success:
                            alertTypeClass = "alert-success";
                            alertIconClass = "fa-check-circle-o";
                            break;

                        case AlertBoxModel.AlertTypeEnum.Info:
                            alertTypeClass = "alert-info";
                            alertIconClass = "fa-info-circle";
                            break;

                        case AlertBoxModel.AlertTypeEnum.Warning:
                            alertTypeClass = "alert-warning";
                            alertIconClass = "fa-exclamation-triangle";
                            break;

                        case AlertBoxModel.AlertTypeEnum.Error:
                            alertTypeClass = "alert-danger";
                            alertIconClass = "fa-minus-circle";
                            break;
                    }
                }

                <div class="alert @alertTypeClass fade show g-my-50" role="alert">
                    <h4 class="h5">
                        <i class="fa @alertIconClass"></i>
                        @Model.Opening
                    </h4>
                    <p class="g-mb-10">
                        @Model.Message
                    </p>

                    @foreach (var action in Model.ActionList)
                    {
                        <a href="@action.Item2" class="btn u-btn-darkgray btn-xs rounded-0">
                            <i class="fa fa-cog g-mr-2"></i>
                            @action.Item1
                        </a>
                    }
                </div>
            </div>
            @await Html.PartialAsync("_FooterLinks4LightPage")
        </div>
    </div>
</section>

NXdrive.Web/Views/Shared/_ColumnsOne.cshtml
@{
    Layout = "_Root";
}
@if (IsSectionDefined("Breadcrumb"))
{
    @section Breadcrumb {
        @RenderSection("Breadcrumb")
    }
}
@await Component.InvokeAsync("Widget", new { widgetZone = PublicWidgetZones.MainColumnBefore })
@RenderBody()
@await Component.InvokeAsync("Widget", new { widgetZone = PublicWidgetZones.MainColumnAfter })





NXdrive.Web/Views/Shared/_ColumnsTwo.cshtml
@{
    Layout = "_Root";
}
@{
    //current category ID
    var currentCategoryId = 0;
    if (Url.ActionContext.RouteData.Values["controller"].ToString().Equals("catalog", StringComparison.InvariantCultureIgnoreCase) &&
        Url.ActionContext.RouteData.Values["action"].ToString().Equals("category", StringComparison.InvariantCultureIgnoreCase))
    {
        currentCategoryId = Convert.ToInt32(Url.ActionContext.RouteData.Values["categoryId"].ToString());
    }


    //current manufacturer ID
    var currentManufacturerId = 0;
    if (Url.ActionContext.RouteData.Values["controller"].ToString().Equals("catalog", StringComparison.InvariantCultureIgnoreCase) &&
        Url.ActionContext.RouteData.Values["action"].ToString().Equals("manufacturer", StringComparison.InvariantCultureIgnoreCase))
    {
        currentManufacturerId = Convert.ToInt32(Url.ActionContext.RouteData.Values["manufacturerId"].ToString());
    }


    //current product ID
    var currentProductId = 0;
    if (Url.ActionContext.RouteData.Values["controller"].ToString().Equals("product", StringComparison.InvariantCultureIgnoreCase) &&
        Url.ActionContext.RouteData.Values["action"].ToString().Equals("productdetails", StringComparison.InvariantCultureIgnoreCase))
    {
        currentProductId = Convert.ToInt32(Url.ActionContext.RouteData.Values["productId"].ToString());
    }
}
@if (IsSectionDefined("Breadcrumb"))
{
    @section Breadcrumb {
        @RenderSection("Breadcrumb")
    } 
}
<div class="side-2">
    @if (IsSectionDefined("left"))
    {
        @RenderSection("left")
    }
    else
    {
        @await Component.InvokeAsync("Widget", new { widgetZone = PublicWidgetZones.LeftSideColumnBefore })
        @await Component.InvokeAsync("CategoryNavigation", new { currentCategoryId = currentCategoryId, currentProductId = currentProductId })
        @await Component.InvokeAsync("Widget", new { widgetZone = PublicWidgetZones.LeftSideColumnAfterCategoryNavigation })
        @await Component.InvokeAsync("ManufacturerNavigation", new { currentManufacturerId = currentManufacturerId })
        @await Component.InvokeAsync("VendorNavigation")
        @await Component.InvokeAsync("RecentlyViewedProductsBlock", new { productThumbPictureSize = 64 })
        @await Component.InvokeAsync("PopularProductTags")
        @await Component.InvokeAsync("PollBlock", new { systemKeyword = "LeftColumnPoll" })
        @await Component.InvokeAsync("Widget", new { widgetZone = PublicWidgetZones.LeftSideColumnAfter })
    }
</div>
<div class="center-2">
    @await Component.InvokeAsync("Widget", new { widgetZone = PublicWidgetZones.MainColumnBefore })
    @RenderBody()
    @await Component.InvokeAsync("Widget", new { widgetZone = PublicWidgetZones.MainColumnAfter })
</div>

NXdrive.Web/Views/Shared/_CreateOrUpdateAddress.cshtml
@model AddressModel

@if (Model.CountryEnabled && Model.StateProvinceEnabled)
{
    //we don't move this script to the footer as it's used in Ajax requests where footer is not available
    <script>
        $(document).ready(function () {
            $("#@Html.IdFor(model => model.CountryId)").change(function () {
            var selectedItem = $(this).val();
            var ddlStates = $("#@Html.IdFor(model => model.StateProvinceId)");
            var statesProgress = $("#states-loading-progress");
            statesProgress.show();
                $.ajax({
                cache: false,
                    type: "GET",
                    url: "@(Url.RouteUrl("GetStatesByCountryId"))",
                    data: { "countryId": selectedItem, "addSelectStateItem": "true" },
                    success: function (data) {
                    ddlStates.html('');
                        $.each(data, function (id, option) {
                        ddlStates.append($('<option></option>').val(option.id).html(option.name));
                    });
                    statesProgress.hide();
                },
                    error: function (xhr, ajaxOptions, thrownError) {
                    alert('Failed to retrieve states.');
                    statesProgress.hide();
                }
            });
        });
    });
    </script>
}
<input asp-for="Id" type="hidden" />
<div class="form-group row mb-4">
    <label asp-for="FirstName" class="col-sm-3 col-form-label"></label>
    <div class="col-sm-9">
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>
</div>
<div class="form-group row mb-4">
    <label asp-for="LastName" class="col-sm-3 col-form-label"></label>
    <div class="col-sm-9">
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>
</div>
<div class="form-group row mb-4">
    <label asp-for="Email" class="col-sm-3 col-form-label"></label>
    <div class="col-sm-9">
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
</div>

@if (Model.CompanyEnabled)
{
    <div class="form-group row mb-4">
        <label asp-for="Company" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9">
            <input asp-for="Company" class="form-control" />
            <span asp-validation-for="Company" class="text-danger"></span>
        </div>
    </div>
}
@if (Model.CountryEnabled)
{
    <div class="form-group row mb-4">
        <label asp-for="CountryId" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9">
            <select asp-for="CountryId" asp-items="Model.AvailableCountries" class="form-control"></select>
            <span asp-validation-for="CountryId" class="text-danger"></span>
        </div>
    </div>
}

@if (Model.CountryEnabled && Model.StateProvinceEnabled)
{
    <div class="form-group row mb-4">
        <label asp-for="StateProvinceId" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9">
            <select asp-for="StateProvinceId" asp-items="Model.AvailableStates" class="form-control"></select>
            <span id="states-loading-progress" style="display: none;" class="please-wait">@T("Common.Wait...")</span>
            <span asp-validation-for="StateProvinceId" class="text-danger"></span>
        </div>
    </div>
}
@if (Model.CountyEnabled)
{
    <div class="form-group row mb-4">
        <label asp-for="County" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9">
            <input asp-for="County" class="form-control" />
            <span asp-validation-for="County" class="text-danger"></span>
        </div>
    </div>
}
@if (Model.CityEnabled)
{
    <div class="form-group row mb-4">
        <label asp-for="City" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9">
            <input asp-for="City" class="form-control" />
            <span asp-validation-for="City" class="text-danger"></span>
        </div>
    </div>
}
@if (Model.StreetAddressEnabled)
{
    <div class="form-group row mb-4">
        <label asp-for="Address1" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9">
            <input asp-for="Address1" class="form-control" />
            <span asp-validation-for="Address1" class="text-danger"></span>
        </div>
    </div>
}
@if (Model.StreetAddress2Enabled)
{
    <div class="form-group row mb-4">
        <label asp-for="Address2" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9">
            <input asp-for="Address2" class="form-control" />
            <span asp-validation-for="Address2" class="text-danger"></span>
        </div>
    </div>
}
@if (Model.ZipPostalCodeEnabled)
{
    <div class="form-group row mb-4">
        <label asp-for="ZipPostalCode" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9">
            <input asp-for="ZipPostalCode" class="form-control" />
            <span asp-validation-for="ZipPostalCode" class="text-danger"></span>
        </div>
    </div>
}
@if (Model.PhoneEnabled)
{
    <div class="form-group row mb-4">
        <label asp-for="PhoneNumber" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9">
            <input asp-for="PhoneNumber" class="form-control u-form-control" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
    </div>
}
@if (Model.FaxEnabled)
{
    <div class="form-group row mb-4">
        <label asp-for="FaxNumber" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9">
            <input asp-for="FaxNumber" class="form-control" />
            <span asp-validation-for="FaxNumber" class="text-danger"></span>
        </div>
    </div>
}

@if (Model.CustomAddressAttributes.Count > 0)
{
    @await Html.PartialAsync("_AddressAttributes", Model.CustomAddressAttributes)
}

NXdrive.Web/Views/Shared/_FooterLinks4LightPage.cshtml
<ul class="nav justify-content-center">
    <li class="nav-item">
        <a href="@Url.RouteUrl("HomePage")" class="nav-link">Home</a>
    </li>
    <li class="nav-item">
        <a href="@Url.RouteUrl("ServicePlans")" target="_blank" class="nav-link">Plans</a>
    </li>
    <li class="nav-item">
        <a href="@Url.RouteUrl("HelpCenter")" target="_blank" class="nav-link">Help</a>
    </li>
    <li class="nav-item">
        <a href="@Url.RouteUrl("Term")" target="_blank" class="nav-link">Term</a>
    </li>
</ul>

NXdrive.Web/Views/Shared/_JavaScriptDisabledWarning.cshtml
@using Nop.Core.Domain.Common
@inject CommonSettings CommonSettings
@if (CommonSettings.DisplayJavaScriptDisabledWarning)
{
    <noscript>
        <div class="noscript">
            <p>
                <strong>JavaScript seems to be disabled in your browser.</strong>
            </p>
            <p>
                You must have JavaScript enabled in your browser to utilize the functionality of
                this website.
            </p>
        </div>
    </noscript>
}

NXdrive.Web/Views/Shared/_OldInternetExplorerWarning.cshtml
@inject IThemeContext ThemeContext
@{
    var currentThemeName = ThemeContext.WorkingThemeName;
    var logoPath = "~/Themes/" + currentThemeName + "/Content/images/ie_warning.jpg";

}
<!--[if lte IE 7]>
    <div style="clear:both;height:59px;text-align:center;position:relative;">
        <a href="http://www.microsoft.com/windows/internet-explorer/default.aspx" target="_blank">
            <img src="@Url.Content(logoPath)" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
        </a>
    </div>
<![endif]-->

NXdrive.Web/Views/Shared/_OrderReviewData.cshtml
@model ShoppingCartModel.OrderReviewDataModel
@if (Model.Display)
{
    <div class="order-review-data">
        <div class="billing-info-wrap">
            <div class="billing-info g-mb-50">
                <h5 class="h5 mb-3">
                    @T("Order.BillingAddress")
                </h5>
                <span class="d-block g-color-gray-dark-v3 g-font-weight-600 mb-2">
                    @Model.BillingAddress.FirstName @Model.BillingAddress.LastName
                </span>
                <address class="media">

                    <div class="d-flex mr-3">
                        <span class="u-icon-v1 g-color-gray-dark-v4"><i class="icon-real-estate-027 u-line-icon-pro"></i></span>
                    </div>

                    <div class="media-body g-color-text">

                        <a href="mailto: @Model.BillingAddress.Email">
                            @Model.BillingAddress.Email
                        </a>
                        <br />

                        @if (Model.BillingAddress.CompanyEnabled && !string.IsNullOrEmpty(Model.BillingAddress.Company))
                        {
                            <em>
                                @Model.BillingAddress.Company
                            </em>
                            <br />
                        }
                        @if (Model.BillingAddress.StreetAddressEnabled)
                        {
                            @Model.BillingAddress.Address1
                            <br />
                        }
                        @if (Model.BillingAddress.StreetAddress2Enabled && !string.IsNullOrEmpty(Model.BillingAddress.Address2))
                        {
                            @Model.BillingAddress.Address2
                            <br />
                        }
                        @if (Model.BillingAddress.CityEnabled && !string.IsNullOrEmpty(Model.BillingAddress.City) ||
                 Model.BillingAddress.CountyEnabled && !string.IsNullOrEmpty(Model.BillingAddress.County) ||
                 Model.BillingAddress.StateProvinceEnabled && !string.IsNullOrEmpty(Model.BillingAddress.StateProvinceName) ||
                 Model.BillingAddress.ZipPostalCodeEnabled && !string.IsNullOrEmpty(Model.BillingAddress.ZipPostalCode))
                        {
                            @if (Model.BillingAddress.CityEnabled && !string.IsNullOrEmpty(Model.BillingAddress.City))
                            {
                                @Model.BillingAddress.City
                                @if (Model.BillingAddress.CountyEnabled && !string.IsNullOrEmpty(Model.BillingAddress.County) ||
                         Model.BillingAddress.StateProvinceEnabled && !string.IsNullOrEmpty(Model.BillingAddress.StateProvinceName) ||
                         Model.BillingAddress.ZipPostalCodeEnabled && !string.IsNullOrEmpty(Model.BillingAddress.ZipPostalCode))
                                {
                                    <text>,</text>
                                }
                            }
                            @if (Model.BillingAddress.CountyEnabled && !string.IsNullOrEmpty(Model.BillingAddress.County))
                            {
                                @Model.BillingAddress.County
                                @if (Model.BillingAddress.StateProvinceEnabled && !string.IsNullOrEmpty(Model.BillingAddress.StateProvinceName) ||
                         Model.BillingAddress.ZipPostalCodeEnabled && !string.IsNullOrEmpty(Model.BillingAddress.ZipPostalCode))
                                {
                                    <text>,</text>
                                }
                            }
                            @if (Model.BillingAddress.StateProvinceEnabled && !string.IsNullOrEmpty(Model.BillingAddress.StateProvinceName))
                            {
                                @Model.BillingAddress.StateProvinceName
                                @if (Model.BillingAddress.ZipPostalCodeEnabled && !string.IsNullOrEmpty(Model.BillingAddress.ZipPostalCode))
                                {
                                    <text>,</text>
                                }
                            }
                            @if (Model.BillingAddress.ZipPostalCodeEnabled && !string.IsNullOrEmpty(Model.BillingAddress.ZipPostalCode))
                            {
                                @Model.BillingAddress.ZipPostalCode
                            }
                            <br />
                        }
                        @if (Model.BillingAddress.CountryEnabled && !string.IsNullOrEmpty(Model.BillingAddress.CountryName))
                        {
                            @Model.BillingAddress.CountryName
                            <br />
                        }
                        @if (!string.IsNullOrEmpty(Model.BillingAddress.FormattedCustomAddressAttributes))
                        {
                            @Html.Raw(Model.BillingAddress.FormattedCustomAddressAttributes)
                            <br />
                        }
                        @if (Model.CustomValues != null)
                        {
                            foreach (var item in Model.CustomValues)
                            {
                                <span class="label">
                                    @item.Key:
                                </span>
                                <span class="value">
                                    @(item.Value != null ? item.Value.ToString() : "")
                                </span>
                                <br />
                            }
                        }
                    </div>

                    @if (Model.BillingAddress.PhoneEnabled)
                    {
                        <div class="media">
                            <div class="d-flex mr-3">
                                <span class="u-icon-v1 g-color-gray-dark-v4"><i class="icon-electronics-005 u-line-icon-pro"></i></span>
                            </div>
                            <div class="media-body g-color-text">
                                @Model.BillingAddress.PhoneNumber
                            </div>
                        </div>
                    }

                    @if (Model.BillingAddress.FaxEnabled)
                    {
                        <div class="media">
                            <div class="d-flex mr-3">
                                <span class="u-icon-v1 g-color-gray-dark-v4"><i class="icon-electronics-005 u-line-icon-pro"></i></span>
                            </div>
                            <div class="media-body g-color-text">
                                @Model.BillingAddress.FaxNumber
                            </div>
                        </div>
                    }
                </address>
            </div>

            @if (!string.IsNullOrEmpty(Model.PaymentMethod))
            {
                <div class="payment-method-info">
                    <h5 class="h5 mb-3">@T("Order.Payment")
                    </h5>

                    <div class="d-flex justify-content-between mb-2">
                        <span class="g-color-black">@T("Order.Payment.Method")</span>
                        <span class="g-color-black g-font-weight-300">@Model.PaymentMethod</span>
                    </div>
                </div>
            }
        </div>

    </div>
}

NXdrive.Web/Views/Shared/_ReferProductModal.cshtml
<style>
    .bootstrap-tagsinput {
        width: 100%;
        padding: 0.25rem 1rem;
        font-size: 1rem;
        font-weight: 400;
        line-height: 2.5;
        color: #1e2022;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #d5dae2;
        border-radius: 0.25rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }
    .bootstrap-tagsinput .tag {
        color: black;
        border: 1px solid #efb225;
        border-radius: 5px;
        padding: 5px 10px;
    }
</style>

<div id="referProductModal" class="js-modal-window u-modal-window" style="width: 680px;">
    <form class="card mb-9" id="refer-product-form">

        <header class="card-header bg-light py-3 px-5">
            <div class="row justify-content-between align-items-center no-gutters">
                <div class="col-9">
                    <h5 class="text-secondary">
                        <i class="fas fa-user-friends text-primary mr-1"></i>
                        <span class="header-title">Refer Service</span>
                    </h5>
                </div>

                <div class="col-3 text-right">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item mr-0">
                            <a class="btn btn-sm btn-icon btn-soft-secondary btn-bg-transparent" href="javascript:;" onclick="Custombox.modal.close();">
                                <span class="fas fa-times btn-icon__inner"></span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </header>

        <div class="card-body pt-3 pb-5 px-5">

            <div class="alert alert-danger" style="display:none;" role="alert">
            </div>

            <nop-antiforgery-token />
            <!-- Leave if for our page-specific script to work on turning it into taginputs -->
            <input class="multiple-emails" name="Emails" placeholder="Emails">
            <textarea class="form-control" name="PersonalMessage" rows="3" placeholder="Personalize your message here" aria-label="Message body"></textarea>

            <hr class="my-4">

            <div class="d-flex justify-content-end">
                <button type="button" class="btn btn-sm btn-primary transition-3d-hover mr-1 submit-btn">
                    <i class="far fa-paper-plane mr-2"></i>Send
                </button>
                <button type="button" class="btn btn-sm btn-soft-secondary transition-3d-hover" onclick="Custombox.modal.close();">
                    <i class="fas fa-times-circle mr-2"></i>Cancel
                </button>
            </div>
        </div>
    </form>
</div>

NXdrive.Web/Views/Shared/_Root4FrontTheme.cshtml
@{
    Layout = "_Root4FrontTheme.Head";
}
@await Html.PartialAsync("_Notifications")
@await Html.PartialAsync("_JavaScriptDisabledWarning")
@await Html.PartialAsync("_OldInternetExplorerWarning")
<main id="content" role="main">
    <!-- Header -->
    <vc:zenith-header version="FrontTheme"></vc:zenith-header>

    @RenderBody()

    <vc:zenith-footer version="FrontTheme"></vc:zenith-footer>

    @await Component.InvokeAsync("EuCookieLaw")
</main>

<div class="u-outer-spaces-helper"></div>

@await Component.InvokeAsync("EuCookieLaw")

NXdrive.Web/Views/Shared/_SentPrivateMessage.cshtml
@model PrivateMessageModel

<div class="message-box" data-message-id="@Model.Id">
    <div class="media mb-3">
        <div class="u-avatar mr-3">
            <img class="img-fluid rounded-circle" src="@Model.CustomProperties["AvatarUrl"]" alt="@Model.CustomerToName">
        </div>
        <div class="media-body">
            <h4 class="d-inline-block mb-1">
                <a class="d-block h6 mb-0" href="#">@Model.CustomerToName</a>
            </h4>
            <small class="d-block text-muted">@Model.CreatedOn</small>
        </div>
    </div>

    <h4 class="h6">
        @Model.Subject
        @if (!Model.IsRead)
        {
            <span class="badge badge-info badge-pill">Not read yet</span>
        }
    </h4>

    <p>@Html.Raw(Model.Message)</p>

    <ul class="list-inline d-flex justify-content-end">
        <li class="list-inline-item">
            <button type="button"
                    class="btn-link btn btn-sm text-secondary ladda-button standalone-btn delete-sent-message"
                    data-ladda-wrapper-id="delete-@Model.Id"
                    data-message-id="@Model.Id"
                    data-color="purple"
                    data-style="expand-right">
                <span class="ladda-label">
                    <i class="far fa-trash-alt mr-1"></i>
                    Delete
                </span>
            </button>
        </li>
    </ul>

    <hr class="my-6">

</div>